config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact

  root to: 'projects#index'

  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about
    end

    def contact
    end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :body, :description, :banner_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavBar">
    <div class = "collapse-bg p-a-1">
        <div class='card'>
            <ul class = "list-group list-group-flush">
                <li class="list-group-item">
                    <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}"%>
                </li>
                <li class="list-group-item">
                    <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}"%>
                </li>
                <li class="list-group-item">
                            <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
                </li>
             </ul>
         </div>
     </div>
</div>

<nav class="navbar navbar-light bg-faded">
    <div class='container'>
        <a class='navbar-brand' href='/'>
        From The Desk of Joseph T Fertitta<span class='light'></span>
         </a>
            <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
                <li class="nav-item">
                    <%= link_to 'Blog', root_path, class: "nav-link #yield(:blog_active)}"%>
                </li>
                <li class="nav-item">
                    <%= link_to 'About', about_path, class: "nav-link #yield(:about_active)}"%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Contact', contact_path, class: "nav-link #yield(:contact_active)}"%>
                </li>
                <li class="nav-item">
                <%= link_to 'Donate'%>
            </li>
            </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Software</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%=action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:about_active, 'active') %>

<h1> about page </h1>

app/views/pages/contact.html.erb
<% provide(:contact_active, 'active') %>
<h1> contact page </h1>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
  <%= form.label :banner_image_url %>
  <%= form.text_field :banner_image_url %>
</div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class='col-sm-6 col-lg-4'>
    <div class="card">
        <div class="card-topper" style='background-image: url (<%= project.banner_image_url %>);'></div>
        <div class="card-block">
            <h4 class="card-title"><%= link_to project.title, project %> </h4>
            <p class="published-date">Published May 02, 2021 </p>
            <p class="card-text"><%= truncate(project.description, length: 130) %></p>
            <%= link_to 'Read', project, class: 'btn btn-read' %>
        </div>
    </div>
</div>

app/views/projects/edit.html.erb
<% provide(:page_title, "Edit #{@project.title}") %>
<% provide(:blog_active, 'active') %>

<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <% @projects.each do |project| %>
    <%= render project %>
  <% end %>
</div>

app/views/projects/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:blog_active, 'active') %>

<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% provide(:page_title, @project.title) %>
<% provide(:blog_active, 'active') %>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @project.title %></h1>
    <p> May 02, 2021</p>
    <%= @project.body %>
  </div>
</div>